# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  docker-compose = {
    pname = "docker-compose";
    version = "v2.31.0";
    src = fetchFromGitHub {
      owner = "docker";
      repo = "compose";
      rev = "v2.31.0";
      fetchSubmodules = false;
      sha256 = "sha256-l+xSd7eIpEy6A1mtx3WrcPQl7071IdJkbHKXbe4uFdA=";
    };
  };
  podman = {
    pname = "podman";
    version = "v5.4.1";
    src = fetchFromGitHub {
      owner = "containers";
      repo = "podman";
      rev = "v5.4.1";
      fetchSubmodules = false;
      sha256 = "sha256-RirMBb45KeBLdBJrRa86WxI4FiXdBar+RnVQ2ezEEYc=";
    };
  };
  vscode-insiders-darwin-arm64 = {
    pname = "vscode-insiders-darwin-arm64";
    version = "5dab7809de7d46dffea7180dddcde7100f2ab4d6";
    src = fetchurl {
      url = "https://vscode.download.prss.microsoft.com/dbazure/download/insider/5dab7809de7d46dffea7180dddcde7100f2ab4d6/VSCode-darwin-arm64.zip";
      sha256 = "sha256-vrnKcGc+4VlCnAq1N8j5cix7nbwcVUXIMYpDakSGCjk=";
    };
  };
  vscode-insiders-linux-arm64 = {
    pname = "vscode-insiders-linux-arm64";
    version = "5dab7809de7d46dffea7180dddcde7100f2ab4d6";
    src = fetchurl {
      url = "https://vscode.download.prss.microsoft.com/dbazure/download/insider/5dab7809de7d46dffea7180dddcde7100f2ab4d6/code-insider-arm64-1765430486.tar.gz";
      sha256 = "sha256-EkPlDgx0KtI9yxGMkrHWAML/je/fXhco84lR95UCieA=";
    };
  };
}
