# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  docker-compose = {
    pname = "docker-compose";
    version = "v2.31.0";
    src = fetchFromGitHub {
      owner = "docker";
      repo = "compose";
      rev = "v2.31.0";
      fetchSubmodules = false;
      sha256 = "sha256-l+xSd7eIpEy6A1mtx3WrcPQl7071IdJkbHKXbe4uFdA=";
    };
  };
  podman = {
    pname = "podman";
    version = "v5.4.1";
    src = fetchFromGitHub {
      owner = "containers";
      repo = "podman";
      rev = "v5.4.1";
      fetchSubmodules = false;
      sha256 = "sha256-RirMBb45KeBLdBJrRa86WxI4FiXdBar+RnVQ2ezEEYc=";
    };
  };
  vscode-insiders-darwin-arm64 = {
    pname = "vscode-insiders-darwin-arm64";
    version = "latest";
    src = fetchurl {
      url = "https://update.code.visualstudio.com/latest/darwin-arm64/insider";
      sha256 = "sha256-Xqs7aSK2ZPPeunm3tQzp7N4EsfovAy6hiRr/eRSShE0=";
    };
  };
  vscode-insiders-darwin-x64 = {
    pname = "vscode-insiders-darwin-x64";
    version = "latest";
    src = fetchurl {
      url = "https://update.code.visualstudio.com/latest/darwin/insider";
      sha256 = "sha256-sa5nIHhWivKDYJzp6pIrjmLLm7Hah4Or/Muun9n9Zo4=";
    };
  };
  vscode-insiders-linux-arm64 = {
    pname = "vscode-insiders-linux-arm64";
    version = "latest";
    src = fetchurl {
      url = "https://update.code.visualstudio.com/latest/linux-arm64/insider";
      sha256 = "sha256-oMruXfJ1CPeXeQIGNkr5mSiWGCgNDAUWFMAbNltE7ro=";
    };
  };
  vscode-insiders-linux-x64 = {
    pname = "vscode-insiders-linux-x64";
    version = "latest";
    src = fetchurl {
      url = "https://update.code.visualstudio.com/latest/linux-x64/insider";
      sha256 = "sha256-0uNCAUZh4OLrSZ1R5LDjRrKjgjLfbqKXJHeqRcHTJrQ=";
    };
  };
}
