# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchurl,
  fetchFromGitHub,
}: {
  docker-compose = {
    pname = "docker-compose";
    version = "v2.31.0";
    src = fetchFromGitHub {
      owner = "docker";
      repo = "compose";
      rev = "v2.31.0";
      fetchSubmodules = false;
      sha256 = "sha256-l+xSd7eIpEy6A1mtx3WrcPQl7071IdJkbHKXbe4uFdA=";
    };
  };
  podman = {
    pname = "podman";
    version = "v5.4.1";
    src = fetchFromGitHub {
      owner = "containers";
      repo = "podman";
      rev = "v5.4.1";
      fetchSubmodules = false;
      sha256 = "sha256-RirMBb45KeBLdBJrRa86WxI4FiXdBar+RnVQ2ezEEYc=";
    };
  };
  rancher-desktop = {
    pname = "rancher-desktop";
    version = "v1.18.2";
    src = fetchurl {
      url = "https://github.com/rancher-sandbox/rancher-desktop/releases/download/v1.18.2/Rancher.Desktop-1.18.2.aarch64.dmg";
      sha256 = "sha256-ss7KnnHysBq422YUVqO2jnf1YQd+prGU/gU17yDm6v0=";
    };
  };
}
