# slacoin@nuxeo.com gnupg keyring (https://github.com/nxmatic/keyhole.git)

Host *.mammoth-skate
  IdentityFile ~/.local/var/run/secrets/ssh-keys/rdp-host
   ForwardAgent yes
   User nxmatic

Host nikopol.mammoth-skae
  HostName nikopol.mammoth-skate.ts.net

Host bioskop.mammoth-skate
  HostName bioskop.mammoth-skate.ts.net

Include ~/.ssh/config.d/zones.d/mammoth-skate.d/*.conf
