# slacoin@nuxeo.com gnupg keyring (https://github.com/nxmatic/keyhole.git)

Host rdp-host.nikopol
   HostName nikopol.local

Host vz-host.nikopol
   HostName nikopol-vz.lan
   User stephane.lacoin
   IdentityFile ~/.local/var/run/secrets/ssh-keys/rdp-host
   IdentitiesOnly yes
   IdentityAgent none
   PreferredAuthentications publickey

Host *.nikopol
   User nxmatic
   IdentityFile ~/.local/var/run/secrets/ssh-keys/rdp-host

Host nixos.nikopol
   HostName nikopol-nixos.local
   
Include ~/.ssh/config.d/zones.d/nikopol.d/*.conf
