[docker-compose]
fetch.github = "docker/compose"
src.manual = "v2.31.0"
[podman]
fetch.github = "containers/podman"
src.manual = "v5.4.1"

[vscode-insiders-linux-x64]
src.manual = "latest"
fetch.url = "https://update.code.visualstudio.com/latest/linux-x64/insider"
fetch.name = "vscode-insiders-linux-x64.tar.gz"

[vscode-insiders-linux-arm64]
src.manual = "latest"
fetch.url = "https://update.code.visualstudio.com/latest/linux-arm64/insider"
fetch.name = "vscode-insiders-linux-arm64.tar.gz"

[vscode-insiders-darwin-x64]
src.manual = "latest"
fetch.url = "https://update.code.visualstudio.com/latest/darwin/insider"
fetch.name = "vscode-insiders-darwin-x64.zip"

[vscode-insiders-darwin-arm64]
src.manual = "latest"
fetch.url = "https://update.code.visualstudio.com/latest/darwin-arm64/insider"
fetch.name = "vscode-insiders-darwin-arm64.zip"
