[docker-compose]
  [docker-compose.fetch]
    github = 'docker/compose'

  [docker-compose.src]
    manual = 'v2.31.0'

[podman]
  [podman.fetch]
    github = 'containers/podman'

  [podman.src]
    manual = 'v5.4.1'

[vscode-insiders-darwin-arm64]
  [vscode-insiders-darwin-arm64.fetch]
    name = 'VSCode-darwin-arm64.zip'
    url = 'https://vscode.download.prss.microsoft.com/dbazure/download/insider/5dab7809de7d46dffea7180dddcde7100f2ab4d6/VSCode-darwin-arm64.zip'

  [vscode-insiders-darwin-arm64.src]
    manual = '5dab7809de7d46dffea7180dddcde7100f2ab4d6'

[vscode-insiders-linux-arm64]
  [vscode-insiders-linux-arm64.fetch]
    name = 'code-insider-arm64-1765430486.tar.gz'
    url = 'https://vscode.download.prss.microsoft.com/dbazure/download/insider/5dab7809de7d46dffea7180dddcde7100f2ab4d6/code-insider-arm64-1765430486.tar.gz'

  [vscode-insiders-linux-arm64.src]
    manual = '5dab7809de7d46dffea7180dddcde7100f2ab4d6'
