{
  config,
  pkgs,
  lib,
  ...
}:

let
  dollar = "$";
  hostname =
    if config.networking.hostName != "" then config.networking.hostName else "nix-darwin-home";
  profile =
    config.profile or {
      name = "default";
      host = {
        hostName = hostname;
      };
    };
  profileName = profile.name;
  hostIdent =
    if (profile.host ? hostAlias && profile.host.hostAlias != null && profile.host.hostAlias != "") then
      profile.host.hostAlias
    else
      profile.host.hostName;
  clientKeyName = builtins.baseNameOf config.sshPaths.privKeyFile;

  userHome =
    if config ? profile && config.profile ? user && config.profile.user ? home then
      toString config.profile.user.home
    else
      "/root";
  # Reuse existing host key generated/managed by NixOS (ed25519 preferred)
  hostKeyPath = "/etc/ssh/ssh_host_ed25519_key"; # runtime path consumed by sshd
  hostCertPath = null; # Add signed host cert later if desired
  keysDir = config.opensshPolicy.keysDir;
  caPublicKeyPath = "${keysDir}/trusted-user-ca.pub"; # generated from all *-ca.pub keys in keysDir

  allPrincipals = [
    "committed"
    "work"
    "nikopol"
    "bioskop"
  ];

  formatPrincipals = principals: lib.concatStringsSep "\n" (map (p: "          - ${p}") principals);

  principalsKeysYamlText = ''
        # Authorized principals metadata for ${hostIdent} (${profileName} profile)
        # Generated by modules/nixos/systemd/openssh.nix (public metadata only).
        profiles:
          committed:
            host:
              principals:
    ${formatPrincipals allPrincipals}
          work:
            host:
              principals:
    ${formatPrincipals allPrincipals}
  '';
  principalsScriptStore = pkgs.replaceVars ../../.common.d/ssh/authorized-principals-command.sh {
    bashTrampoline = "${../../.common.d/shell.d/nix-bash-trampoline.sh}";
    logger = logger;
  };
  groupKeysScriptStore = pkgs.replaceVars ../../.common.d/ssh/ssh-group-authorized-keys.sh {
    bashTrampoline = "${../../.common.d/shell.d/nix-bash-trampoline.sh}";
    logger = logger;
    authorizedKeysDir = config.opensshPolicy.authorizedKeysDir;
  };
  # Use the wrapped activation logger packaged into the system closure
  logger = config.nixBashLogger.script;
  loggerTag = "nixos.activationScripts.sshGroupKeys";
  hasSopsInstallSecretsService = builtins.hasAttr "sops-install-secrets" config.systemd.services;
  homeManagerServiceName = "home-manager-${config.profile.user.name}";
  hasHomeManagerService = builtins.hasAttr homeManagerServiceName config.systemd.services;
  hostkeyEnrollmentCheckTag = "nixos.services.ndh.hostkeyEnrollmentCheck";
  hostkeyEnrollmentSyncTag = "nixos.services.ndh.hostkeyEnrollmentSync";
  hostkeyEnrollmentCheckScript = pkgs.replaceVars ./openssh.d/hostkey-enrollment-check.sh {
    bashTrampoline = "${../../.common.d/shell.d/nix-bash-trampoline.sh}";
    logger = logger;
    logTag = hostkeyEnrollmentCheckTag;
    userPrivateSourceDir = config.sshPaths.secretsKeysDir;
    userCaSourceDir = config.sshPaths.authoritySecretsDir;
    systemHostKeyPub = "${hostKeyPath}.pub";
    clientKeyName = clientKeyName;
  };
  hostkeyEnrollmentSyncScript = pkgs.replaceVars ./openssh.d/hostkey-enrollment-sync.sh {
    bashTrampoline = "${../../.common.d/shell.d/nix-bash-trampoline.sh}";
    logger = logger;
    logTag = hostkeyEnrollmentSyncTag;
    clientPrivateSource = config.sshPaths.privKeyFile;
    clientUserCertSource = config.sshPaths.userCertPublic;
    fallbackHost = config.limaHost.hostName;
    remoteUser = config.profile.user.name;
    remoteRepo = "/var/lib/git/nxmatic/nix-darwin-home";
    guestName = config.limaHost.guestName;
  };
in
{
  imports = [
    ../../.common.d/openssh-policy.nix
    ../../.common.d/ssh-paths.nix
  ];

  opensshPolicy = {
    enable = true;
    platformRendersAuthorizedKeysFile = lib.mkDefault false;
    setEnvPath = lib.mkDefault "/run/wrappers/bin:/run/current-system/sw/bin:/bin:/usr/bin";
    nonInteractivePrimaryPath = lib.mkDefault "/run/wrappers/bin";
    trustedCAPath = caPublicKeyPath;
    principalsCommandSource = principalsScriptStore;
    groupKeysCommandSource = groupKeysScriptStore;
    hostKeyPaths = [ hostKeyPath ];

    # Force IPv4 only for SSH server
    extraSettings = {
      AddressFamily = "inet";
      # Bootstrap requirement: allow root with key-based auth only.
      PermitRootLogin = "prohibit-password";
    };
  };

  services.openssh = {
    enable = true;
    authorizedKeysFiles = lib.mkForce config.opensshPolicy.authorizedKeysFiles;
    settings = config.opensshPolicy.settings // {
      UsePAM = true;
      # Allow client to specify which address to bind for remote forwardsssh
      GatewayPorts = "clientspecified";
    };
    # Render shared daemon Include globs
    extraConfig =
      (
        let
          lines = builtins.map (g: "Include ${g}") config.opensshPolicy.includeDaemonGlobs;
        in
        lib.concatStringsSep "\n" lines + "\n"
      )
      + ''
        # Enable remote forwarding of Unix domain sockets (for GPG agent forwarding)
        StreamLocalBindUnlink yes
        AllowStreamLocalForwarding yes
      '';
  };

  # OpenSSH client configuration: allow includes for drop-ins under /etc/ssh/ssh_config.d
  programs.ssh = {
    extraConfig = ''
      Host *
        AddressFamily inet
        ServerAliveInterval 30
        ServerAliveCountMax 3
    ''
    + (
      let
        lines = builtins.map (g: "Include ${g}") config.opensshPolicy.includeClientGlobs;
      in
      "\n" + lib.concatStringsSep "\n" lines + "\n"
    );
  };

  # Ensure the group authorized keys directory exists and create keys
  system.activationScripts = {
    sshGroupKeys = {
      text = builtins.readFile (
        pkgs.replaceVars ./openssh.d/activation.sh {
          bash = "${pkgs.bash}/bin/bash";
          bashTrampoline = "${../../.common.d/shell.d/nix-bash-trampoline.sh}";
          authorizedKeysDir = config.opensshPolicy.authorizedKeysDir;
          keysDir = config.opensshPolicy.keysDir;
          hostname = hostname;
          principalsCommand = config.opensshPolicy.canonicalPrincipalsCommandName;
          groupCommand = config.opensshPolicy.canonicalGroupKeysCommandName;
          principalsScript = principalsScriptStore;
          groupKeysScript = groupKeysScriptStore;
          profileUserName = config.profile.user.name;
          logger = logger;
          loggerTag = loggerTag;
          userPrivateSourceDir = config.sshPaths.secretsKeysDir;
          userCaSourceDir = config.sshPaths.authoritySecretsDir;
          clientKeyName = clientKeyName;
        }
      );
    };
  };

  # ssh non-interactive session finds the setuid sudo via /bin or /usr/bin
  systemd.tmpfiles.rules = [
    "z ${config.sshPaths.secretsRootDir} 0700 ${config.profile.user.name} ${config.profile.user.name} - -"
    "z ${config.sshPaths.secretsKeysDir} 0700 ${config.profile.user.name} ${config.profile.user.name} - -"
    "d /run/secrets/nix-darwin-home 0755 root root - -"
    "z ${config.sshPaths.authoritySecretsDir} 0755 ${config.profile.user.name} ${config.profile.user.name} - -"
    "L+ /bin/sudo - - - - /run/wrappers/bin/sudo"
    "L+ /usr/bin/sudo - - - - /run/wrappers/bin/sudo"
    "L+ /bin/bash - - - - /run/current-system/sw/bin/bash"
    "d /run/ndh/ssh 0775 ${config.profile.user.name} ${config.profile.user.name} - -"
  ];

  # Ensure all systemd services (including sshd) inherit a wrapper-first PATH
  systemd.globalEnvironment.PATH = config.opensshPolicy.setEnvPath;

  systemd.services.io-nxmatic-nix-darwin-home-hostkey-enrollment-check = {
    description = "Check whether host key enrollment into encrypted secrets is required (@codebase)";
    wantedBy = [ "sshd.service" ];
    before = [ "sshd.service" ];
    wants = lib.optionals hasSopsInstallSecretsService [ "sops-install-secrets.service" ];
    after = lib.optionals hasSopsInstallSecretsService [ "sops-install-secrets.service" ];
    path = with pkgs; [
      coreutils
      gawk
      openssh
      util-linux
      yq-go
    ];
    serviceConfig = {
      Type = "oneshot";
      User = config.profile.user.name;
      Group = config.profile.user.name;
      Environment = [ "HOME=${userHome}" ];
      ExecStart = "${pkgs.bash}/bin/bash ${hostkeyEnrollmentCheckScript}";
    };
  };

  systemd.services.io-nxmatic-nix-darwin-home-hostkey-enrollment-sync = {
    description = "Run remote hostkey enrollment sync when drift marker is present (@codebase)";
    wantedBy = [ "io-nxmatic-nix-darwin-home-contributed.target" ];
    wants = [
      "network-online.target"
      "io-nxmatic-nix-darwin-home-hostkey-enrollment-check.service"
    ]
    ++ lib.optionals hasHomeManagerService [ "${homeManagerServiceName}.service" ];
    after = [
      "network-online.target"
      "io-nxmatic-nix-darwin-home-hostkey-enrollment-check.service"
    ]
    ++ lib.optionals hasHomeManagerService [ "${homeManagerServiceName}.service" ];
    unitConfig.ConditionPathExists = "/run/ndh/ssh/hostkey-enrollment-state.yaml";
    path = with pkgs; [
      coreutils
      gawk
      openssh
      util-linux
      yq-go
    ];
    serviceConfig = {
      Type = "oneshot";
      User = config.profile.user.name;
      Group = config.profile.user.name;
      Environment = [ "HOME=${userHome}" ];
      ExecStart = "${pkgs.bash}/bin/bash ${hostkeyEnrollmentSyncScript}";
    };
  };

  # Provide principals metadata in a system-readable location for
  # AuthorizedPrincipalsCommand (which runs as an unprivileged user).
  environment.etc."ssh/keys.yaml".text = principalsKeysYamlText;
}
