{
  config,
  pkgs,
  lib,
  ...
}:

let
  dollar = "$";
  hostname =
    if config.networking.hostName != "" then config.networking.hostName else "nix-darwin-home";
  profile =
    config.profile or {
      name = "default";
      host = {
        hostName = hostname;
      };
    };
  profileName = profile.name;
  hostIdent =
    if (profile.host ? hostAlias && profile.host.hostAlias != null && profile.host.hostAlias != "") then
      profile.host.hostAlias
    else
      profile.host.hostName;

  userHome =
    if config ? profile && config.profile ? user && config.profile.user ? home then
      toString config.profile.user.home
    else
      "/root";
  # Reuse existing host key generated/managed by NixOS (ed25519 preferred)
  hostKeyPath = "/etc/ssh/ssh_host_ed25519_key"; # runtime path consumed by sshd
  hostCertPath = null; # Add signed host cert later if desired
  keysDir = config.opensshPolicy.keysDir;
  caPublicKeyPath = "${keysDir}/trusted-user-ca.pub"; # generated from all *-ca.pub keys in keysDir

  allPrincipals = [
    "committed"
    "work"
    "alcide"
    "bioskop"
  ];

  formatPrincipals = principals: lib.concatStringsSep "\n" (map (p: "          - ${p}") principals);

  principalsKeysYamlText = ''
    # Authorized principals metadata for ${hostIdent} (${profileName} profile)
    # Generated by modules/nixos/systemd/openssh.nix (public metadata only).
    profiles:
      committed:
        host:
          principals:
${formatPrincipals allPrincipals}
      work:
        host:
          principals:
${formatPrincipals allPrincipals}
  '';
  principalsScriptStore = pkgs.writeText "ssh-authorized-principals-command.sh" (
    builtins.readFile ../../common/ssh/authorized-principals-command.sh
  );
  groupKeysScriptStore = pkgs.replaceVars ../../common/ssh/ssh-group-authorized-keys.sh {
    authorizedKeysDir = config.opensshPolicy.authorizedKeysDir;
  };
  # Use the wrapped activation logger packaged into the system closure
  activationLogger = config.activation.loggerScript;
  activationTag = "nixos.activationScripts.sshGroupKeys";
in
{
  imports = [ ../../common/openssh-policy.nix ];

  opensshPolicy = {
    enable = true;
    platformRendersAuthorizedKeysFile = lib.mkDefault false;
    setEnvPath = lib.mkDefault "/run/wrappers/bin:/run/current-system/sw/bin:/bin:/usr/bin";
    nonInteractivePrimaryPath = lib.mkDefault "/run/wrappers/bin";
    trustedCAPath = caPublicKeyPath;
    principalsCommandSource = principalsScriptStore;
    groupKeysCommandSource = groupKeysScriptStore;
    hostKeyPaths = [ hostKeyPath ];

    # Force IPv4 only for SSH server
    extraSettings = {
      AddressFamily = "inet";
    };
  };

  services.openssh = {
    enable = true;
    authorizedKeysFiles = lib.mkForce config.opensshPolicy.authorizedKeysFiles;
    settings = config.opensshPolicy.settings // {
      UsePAM = true;
      # Allow client to specify which address to bind for remote forwardsssh
      GatewayPorts = "clientspecified";
    };
    # Render shared daemon Include globs
    extraConfig =
      (
        let
          lines = builtins.map (g: "Include ${g}") config.opensshPolicy.includeDaemonGlobs;
        in
        lib.concatStringsSep "\n" lines + "\n"
      )
      + ''
        # Enable remote forwarding of Unix domain sockets (for GPG agent forwarding)
        StreamLocalBindUnlink yes
        AllowStreamLocalForwarding yes
      '';
  };

  # OpenSSH client configuration: allow includes for drop-ins under /etc/ssh/ssh_config.d
  programs.ssh = {
    extraConfig = ''
      Host *
        AddressFamily inet
        ServerAliveInterval 30
        ServerAliveCountMax 3
    ''
    + (
      let
        lines = builtins.map (g: "Include ${g}") config.opensshPolicy.includeClientGlobs;
      in
      "\n" + lib.concatStringsSep "\n" lines + "\n"
    );
  };

  # Ensure the group authorized keys directory exists and create keys
  system.activationScripts = {
    sshGroupKeys = {
      text = builtins.readFile (
        pkgs.replaceVars ./openssh.d/activation.sh {
          keysDir = config.opensshPolicy.keysDir;
          hostname = hostname;
          sshKeygen = "${pkgs.openssh}/bin/ssh-keygen";
          principalsCommand = config.opensshPolicy.canonicalPrincipalsCommandName;
          groupCommand = config.opensshPolicy.canonicalGroupKeysCommandName;
          principalsScript = principalsScriptStore;
          groupKeysScript = groupKeysScriptStore;
          activationLogger = activationLogger;
          activationTag = activationTag;
          userCaSourceDir = "${userHome}/.ssh/keys.d";
        }
      );
    };
  };

  # ssh non-interactive session finds the setuid sudo via /bin or /usr/bin
  systemd.tmpfiles.rules = [
    "L+ /bin/sudo - - - - /run/wrappers/bin/sudo"
    "L+ /usr/bin/sudo - - - - /run/wrappers/bin/sudo"
    "L+ /bin/bash - - - - /run/current-system/sw/bin/bash"
  ];

  # Ensure all systemd services (including sshd) inherit a wrapper-first PATH
  systemd.globalEnvironment.PATH = config.opensshPolicy.setEnvPath;

  # Provide principals metadata in a system-readable location for
  # AuthorizedPrincipalsCommand (which runs as an unprivileged user).
  environment.etc."ssh/keys.yaml".text = principalsKeysYamlText;
}
