{
  config,
  pkgs,
  lib,
  ...
}:

let
  dollar = "$";
  hostname =
    if config.networking.hostName != "" then config.networking.hostName else "nix-darwin-home";
  profile =
    config.profile or {
      name = "default";
      host = {
        hostName = hostname;
      };
    };
  profileName = profile.name;
  hostIdent =
    if (profile.host ? hostAlias && profile.host.hostAlias != null && profile.host.hostAlias != "") then
      profile.host.hostAlias
    else
      profile.host.hostName;

  userHome =
    if config ? profile && config.profile ? user && config.profile.user ? home then
      toString config.profile.user.home
    else
      "/root";
  # Reuse existing host key generated/managed by NixOS (ed25519 preferred)
  hostKeyPath = "/etc/ssh/ssh_host_ed25519_key"; # runtime path consumed by sshd
  hostCertPath = null; # Add signed host cert later if desired
  keysDir = config.opensshPolicy.keysDir;
  caPublicKeyPath = "${keysDir}/trusted-user-ca.pub"; # generated from all *-ca.pub keys in keysDir

  allPrincipals = [
    "committed"
    "work"
    "alcide"
    "bioskop"
  ];

  formatPrincipals = principals: lib.concatStringsSep "\n" (map (p: "          - ${p}") principals);

  principalsKeysYamlText = ''
    # Authorized principals metadata for ${hostIdent} (${profileName} profile)
    # Generated by modules/nixos/systemd/openssh.nix (public metadata only).
    profiles:
      committed:
        host:
          principals:
${formatPrincipals allPrincipals}
      work:
        host:
          principals:
${formatPrincipals allPrincipals}
  '';
  principalsScriptStore = pkgs.replaceVars ../../common/ssh/authorized-principals-command.sh {
    bashBin = "${pkgs.bash}/bin/bash";
    yqBin = "${pkgs.yq-go}/bin/yq";
    scriptPath = config.opensshPolicy.setEnvPath;
  };
  groupKeysScriptStore = pkgs.replaceVars ../../common/ssh/ssh-group-authorized-keys.sh {
    bashBin = "${pkgs.bash}/bin/bash";
    scriptPath = config.opensshPolicy.setEnvPath;
    authorizedKeysDir = config.opensshPolicy.authorizedKeysDir;
  };
  # Use the wrapped activation logger packaged into the system closure
  activationLogger = config.activation.loggerScript;
  activationTag = "nixos.activationScripts.sshGroupKeys";
  hasSopsInstallSecretsService = builtins.hasAttr "sops-install-secrets" config.systemd.services;
  hostkeyEnrollmentCheckTag = "nixos.services.nxmatic.hostkeyEnrollmentCheck";
  hostkeyEnrollmentSyncTag = "nixos.services.nxmatic.hostkeyEnrollmentSync";
  hostkeyEnrollmentCheckScript = pkgs.replaceVars ./openssh.d/hostkey-enrollment-check.sh {
    loggerBin = pkgs.util-linux;
    sshKeygen = "${pkgs.openssh}/bin/ssh-keygen";
    logTag = hostkeyEnrollmentCheckTag;
    userPrivateSourceDir = config.sshPaths.perUserSecretsDir;
    userCaSourceDir = config.sshPaths.systemSecretsDir;
    systemHostKeyPub = "${hostKeyPath}.pub";
  };
  hostkeyEnrollmentSyncScript = pkgs.replaceVars ./openssh.d/hostkey-enrollment-sync.sh {
    loggerBin = pkgs.util-linux;
    sshBin = pkgs.openssh;
    sshKeygen = pkgs.openssh;
    yqBin = pkgs.yq-go;
    logTag = hostkeyEnrollmentSyncTag;
    runtimeSecretsKeysYaml = config.sshPaths.runtimeSecretsKeysYaml;
    clientPrivateSource = config.sshPaths.privKeyFile;
    clientUserCertSource = "${config.sshPaths.perUserSecretsDir}/rdp-host-cert.pub";
    fallbackHost = config.limaHost.hostName;
    remoteUser = config.profile.user.name;
    remoteRepo = "/var/lib/git/nxmatic/nix-darwin-home";
    guestName = config.limaHost.guestName;
  };
in
{
  imports = [
    ../../common/openssh-policy.nix
    ../../common/ssh-paths.nix
  ];

  opensshPolicy = {
    enable = true;
    platformRendersAuthorizedKeysFile = lib.mkDefault false;
    setEnvPath = lib.mkDefault "/run/wrappers/bin:/run/current-system/sw/bin:/bin:/usr/bin";
    nonInteractivePrimaryPath = lib.mkDefault "/run/wrappers/bin";
    trustedCAPath = caPublicKeyPath;
    principalsCommandSource = principalsScriptStore;
    groupKeysCommandSource = groupKeysScriptStore;
    hostKeyPaths = [ hostKeyPath ];

    # Force IPv4 only for SSH server
    extraSettings = {
      AddressFamily = "inet";
      # Bootstrap requirement: allow root with key-based auth only.
      PermitRootLogin = "prohibit-password";
    };
  };

  services.openssh = {
    enable = true;
    authorizedKeysFiles = lib.mkForce config.opensshPolicy.authorizedKeysFiles;
    settings = config.opensshPolicy.settings // {
      UsePAM = true;
      # Allow client to specify which address to bind for remote forwardsssh
      GatewayPorts = "clientspecified";
    };
    # Render shared daemon Include globs
    extraConfig =
      (
        let
          lines = builtins.map (g: "Include ${g}") config.opensshPolicy.includeDaemonGlobs;
        in
        lib.concatStringsSep "\n" lines + "\n"
      )
      + ''
        # Enable remote forwarding of Unix domain sockets (for GPG agent forwarding)
        StreamLocalBindUnlink yes
        AllowStreamLocalForwarding yes
      '';
  };

  # OpenSSH client configuration: allow includes for drop-ins under /etc/ssh/ssh_config.d
  programs.ssh = {
    extraConfig = ''
      Host *
        AddressFamily inet
        ServerAliveInterval 30
        ServerAliveCountMax 3
    ''
    + (
      let
        lines = builtins.map (g: "Include ${g}") config.opensshPolicy.includeClientGlobs;
      in
      "\n" + lib.concatStringsSep "\n" lines + "\n"
    );
  };

  # Ensure the group authorized keys directory exists and create keys
  system.activationScripts = {
    sshGroupKeys = {
      text = builtins.readFile (
        pkgs.replaceVars ./openssh.d/activation.sh {
          authorizedKeysDir = config.opensshPolicy.authorizedKeysDir;
          keysDir = config.opensshPolicy.keysDir;
          hostname = hostname;
          sshKeygen = "${pkgs.openssh}/bin/ssh-keygen";
          principalsCommand = config.opensshPolicy.canonicalPrincipalsCommandName;
          groupCommand = config.opensshPolicy.canonicalGroupKeysCommandName;
          principalsScript = principalsScriptStore;
          groupKeysScript = groupKeysScriptStore;
          profileUserName = config.profile.user.name;
          activationLogger = activationLogger;
          activationTag = activationTag;
          userPrivateSourceDir = config.sshPaths.perUserSecretsDir;
          userCaSourceDir = config.sshPaths.systemSecretsDir;
        }
      );
    };
  };

  # ssh non-interactive session finds the setuid sudo via /bin or /usr/bin
  systemd.tmpfiles.rules = [
    "d ${config.sshPaths.perUserSecretsRoot} 0755 root root - -"
    "d ${config.sshPaths.perUserSecretsDir} 0700 ${config.profile.user.name} ${config.profile.user.name} - -"
    "d /run/secrets/nix-darwin-home 0755 root root - -"
    "d ${config.sshPaths.systemSecretsDir} 0755 ${config.profile.user.name} ${config.profile.user.name} - -"
    "L+ /bin/sudo - - - - /run/wrappers/bin/sudo"
    "L+ /usr/bin/sudo - - - - /run/wrappers/bin/sudo"
    "L+ /bin/bash - - - - /run/current-system/sw/bin/bash"
  ];

  # Ensure all systemd services (including sshd) inherit a wrapper-first PATH
  systemd.globalEnvironment.PATH = config.opensshPolicy.setEnvPath;

  systemd.services.nxmatic-hostkey-enrollment-check = {
    description = "Check whether host key enrollment into encrypted secrets is required (@codebase)";
    wantedBy = [ "sshd.service" ];
    before = [ "sshd.service" ];
    wants = lib.optionals hasSopsInstallSecretsService [ "sops-install-secrets.service" ];
    after = lib.optionals hasSopsInstallSecretsService [ "sops-install-secrets.service" ];
    serviceConfig = {
      Type = "oneshot";
      ExecStart = "${pkgs.bash}/bin/bash ${hostkeyEnrollmentCheckScript}";
    };
  };

  systemd.services.nxmatic-hostkey-enrollment-sync = {
    description = "Run remote hostkey enrollment sync when drift marker is present (@codebase)";
    wantedBy = [ "multi-user.target" ];
    wants = [
      "network-online.target"
      "nxmatic-hostkey-enrollment-check.service"
    ];
    after = [
      "network-online.target"
      "nxmatic-hostkey-enrollment-check.service"
    ];
    unitConfig.ConditionPathExists = "/run/nxmatic/ssh/hostkey-enrollment-required";
    serviceConfig = {
      Type = "oneshot";
      ExecStart = "${pkgs.bash}/bin/bash ${hostkeyEnrollmentSyncScript}";
    };
  };

  # Provide principals metadata in a system-readable location for
  # AuthorizedPrincipalsCommand (which runs as an unprivileged user).
  environment.etc."ssh/keys.yaml".text = principalsKeysYamlText;
}
