# Headscale bootstrap daemon — runs as a user LaunchAgent on each
# operator Darwin host.  Owns the tailnet control-plane during the
# bootstrap phase, before the rke2-hosted production instance exists.
#
# State lives under `~/Library/Application Support/Headscale/`, matching
# macOS conventions for user daemons (Time Machine-backed up,
# sandbox-friendly).  The binary comes from pkgs.headscale.
#
# Policy is pinned to the Nix-store copy of
# `catalog.headscale.aclPolicyFile`; reloading the daemon re-reads it,
# so editing the ACL + running `darwin-rebuild switch` is the full
# apply cycle — no separate `headscale policy set` post-activation
# hook needed.
#
# Clients authenticate via pre-auth keys.  Keys are created on first
# use with `headscale preauthkeys create --user <user>`; they are NOT
# provisioned by this module (one-time bootstrap concern).  Once a
# client registers, re-registrations use the stored node key.
{
  config,
  pkgs,
  lib,
  ndh,
  ...
}:

with lib;

let
  cfg = config.services.headscaleBootstrap;
  catalog = ndh.context.catalog;
  headscaleCatalog = catalog.headscale;
  hostName = config.networking.hostName or "localhost";

  # Clients always resolve `aliasName` via mDNS to the host currently
  # holding role = "primary"; the daemon itself is told to issue
  # certificates and registration URLs under that same alias, so a
  # standby→primary flip on a different host is transparent at the
  # tailnet level (same server_url, new backing IP).
  serverUrl = headscaleCatalog.aliasUrl;

  stateDir = "${config.users.users.${config.system.primaryUser}.home}/Library/Application Support/Headscale";
  configFile = "${stateDir}/config.yaml";

  # Resolve the mdns-publish binary through the current Darwin pkgs
  # set.  Exposed at flake level as `packages.<system>.ndh-mdns-publish`
  # (see packages/ndh-mdns-publish/).
  mdnsPublish = pkgs.callPackage ../../packages/ndh-mdns-publish { };

  # Headscale config.yaml.  Values substituted in from the catalog.
  # Everything pinned to the state dir so re-activation doesn't relocate
  # running state.  `policy.path` resolves to the Nix store — the file
  # is a symlink target into the flake closure, immutable per generation.
  headscaleConfigYaml = pkgs.writeText "headscale-config.yaml" ''
    # Generated by modules/darwin/headscale-daemon.nix — do not edit by
    # hand.  Persistent state (DB, keys) lives alongside this file under
    # ${stateDir}; the config itself is re-rendered on every
    # darwin-rebuild switch.

    server_url: ${serverUrl}
    listen_addr: 0.0.0.0:${toString headscaleCatalog.listenPort}

    # Metrics listener on localhost only — exposing is optional.
    metrics_listen_addr: 127.0.0.1:${toString (headscaleCatalog.listenPort + 1)}

    # State material headscale creates lazily if missing.
    private_key_path: ${stateDir}/private.key
    noise:
      private_key_path: ${stateDir}/noise_private.key

    # SQLite is fine for a single-operator bootstrap instance.
    database:
      type: sqlite3
      sqlite:
        path: ${stateDir}/db.sqlite

    # ACL policy sourced from the flake catalog.  Store-path means
    # reloading reads whatever the current generation pins; to change
    # the policy, edit catalog/headscale/acl.hujson + darwin-rebuild
    # switch.
    policy:
      mode: file
      path: ${headscaleCatalog.aclPolicyFile}

    # DNS is kept minimal: no MagicDNS override, no extra records.
    # Clients already get their own mDNS resolution; MagicDNS adds a
    # layer we don't need for the 2-operator fleet.
    dns:
      magic_dns: true
      base_domain: mammoth-skate.ts.net
      nameservers:
        global:
          - 1.1.1.1
          - 8.8.8.8

    # Logging: journal-style, info level, stderr so launchd captures
    # into ~/Library/Logs.
    log:
      level: info
      format: text

    # DERP (relays): use the public Tailscale DERP map.  Good enough
    # for LAN + cross-LAN; a self-hosted DERP is a future follow-up.
    derp:
      server:
        enabled: false
      urls:
        - https://controlplane.tailscale.com/derpmap/default
      auto_update_enabled: true
      update_frequency: 24h

    # Disable features we don't use.
    ephemeral_node_inactivity_timeout: 30m
    unix_socket: ${stateDir}/headscale.sock
    unix_socket_permission: "0770"
  '';

  # Thin wrapper that ensures the state dir exists + symlinks the
  # Nix-store config.yaml into it before exec'ing headscale serve.
  # Runtime state (db, keys) remains outside the store; only config is
  # store-pinned.
  headscaleLauncher = pkgs.writeShellScript "headscale-bootstrap-launcher" ''
    set -euo pipefail

    STATE_DIR=${lib.escapeShellArg stateDir}
    CONFIG_LINK=${lib.escapeShellArg configFile}
    CONFIG_SRC=${headscaleConfigYaml}

    mkdir -p "$STATE_DIR"
    chmod 0700 "$STATE_DIR"

    # Symlink so a config edit (via darwin-rebuild switch) is picked up
    # on next daemon restart without copy semantics.  Headscale doesn't
    # care whether the path is a symlink.
    ln -sfn "$CONFIG_SRC" "$CONFIG_LINK"

    exec ${lib.getExe pkgs.headscale} --config "$CONFIG_LINK" serve
  '';
in
{
  options.services.headscaleBootstrap = {
    role = mkOption {
      type = types.enum [ "primary" "standby" "none" ];
      default = "none";
      description = ''
        This host's role in the headscale bootstrap topology.

          primary — run the daemon AND publish the fleet-scoped mDNS
                    alias (catalog.headscale.aliasName) so clients
                    resolve aliasUrl to this host.  Exactly one host
                    should be primary at a time.
          standby — install the headscale CLI + config but do NOT run
                    the daemon and do NOT publish the alias.  Intended
                    for a host that takes over by manually flipping
                    its role to "primary" (and simultaneously
                    demoting the previous primary) during an outage.
                    The config + state dir are ready so promotion
                    needs no rebuild.
          none    — do nothing.  Host neither runs the daemon nor
                    advertises the alias.

        Flip roles by editing host profile, committing, and rolling
        out `darwin-rebuild switch` on both affected hosts.  Clients
        pointed at aliasUrl continue without re-registration because
        the mDNS alias follows ownership transparently.
      '';
    };
  };

  config = mkMerge [
    # Everything except the running daemons — CLI, config, state dir
    # setup — applies to both `primary` and `standby` so the latter is
    # promotion-ready with no further rebuild.
    (mkIf (cfg.role != "none") {
      # Install the CLI system-wide so the operator can run
      # `headscale users create`, `headscale preauthkeys create`, etc.
      # without fishing for the store path.  Available on both primary
      # and standby so a promoted standby can issue preauth keys
      # against the migrated DB immediately.
      environment.systemPackages = [
        pkgs.headscale
        mdnsPublish
      ];

      # Register the port in /etc/services so `lsof -iTCP -sTCP:LISTEN`,
      # netstat, and similar tools render a descriptive name.  macOS
      # ships /etc/services as a real file (not nix-darwin managed), so
      # we append via activation rather than environment.etc.
      system.activationScripts.postActivation.text = lib.mkAfter ''
        if ! grep -qE '^${headscaleCatalog.serviceName}\s+${toString headscaleCatalog.listenPort}/tcp' /etc/services 2>/dev/null; then
          printf '%s\n' '${headscaleCatalog.serviceName} ${toString headscaleCatalog.listenPort}/tcp # Headscale bootstrap control-plane (modules/darwin/headscale-daemon.nix)' >> /etc/services
        fi
      '';
    })

    # Primary-only: the two LaunchAgents that together own the alias
    # identity (daemon + mdns publisher).  Both must run on exactly
    # one host at a time; the `role = "primary"` gate enforces this
    # per-host, and the operator is responsible for not flipping two
    # hosts to primary simultaneously.
    (mkIf (cfg.role == "primary") {
      launchd.user.agents.headscale-bootstrap = {
        command = "${headscaleLauncher}";
        serviceConfig = {
          Label = "io.nxmatic.nix-darwin-home.headscale-bootstrap";
          # Restart on crash.  Headscale is long-lived; transient
          # failures (port binding, DB lock) resolve themselves.
          KeepAlive = true;
          RunAtLoad = true;
          # Logs: stdout/stderr both go to the user's Logs folder so
          # `tail -f ~/Library/Logs/headscale-bootstrap.log` works.
          StandardOutPath = "${config.users.users.${config.system.primaryUser}.home}/Library/Logs/headscale-bootstrap.log";
          StandardErrorPath = "${config.users.users.${config.system.primaryUser}.home}/Library/Logs/headscale-bootstrap.err.log";
          # launchd policy hints.
          ProcessType = "Background";
          LowPriorityIO = true;
        };
      };

      # mDNS alias: publishes `<aliasName> A <this-host-IP>` for the
      # lifetime of the agent.  On SIGTERM the publisher sends a
      # goodbye packet so clients drop the record; launchd will
      # restart on crash (KeepAlive) but briefly leave the alias
      # unresolved during the gap.  Clients retry at their own pace.
      launchd.user.agents.headscale-mdns-publish = {
        command = "${lib.getExe mdnsPublish} --name=${headscaleCatalog.serviceName} --host=${lib.escapeShellArg (lib.removeSuffix ".local" headscaleCatalog.aliasName)} --port=${toString headscaleCatalog.listenPort}";
        serviceConfig = {
          Label = "io.nxmatic.nix-darwin-home.headscale-mdns-publish";
          KeepAlive = true;
          RunAtLoad = true;
          StandardOutPath = "${config.users.users.${config.system.primaryUser}.home}/Library/Logs/headscale-mdns-publish.log";
          StandardErrorPath = "${config.users.users.${config.system.primaryUser}.home}/Library/Logs/headscale-mdns-publish.err.log";
          ProcessType = "Background";
          LowPriorityIO = true;
        };
      };
    })
  ];
}
