# Headscale bootstrap daemon — runs as a user LaunchAgent on each
# operator Darwin host.  Owns the tailnet control-plane during the
# bootstrap phase, before the rke2-hosted production instance exists.
#
# State lives under `~/Library/Application Support/Headscale/`, matching
# macOS conventions for user daemons (Time Machine-backed up,
# sandbox-friendly).  The binary comes from pkgs.headscale.
#
# Policy is pinned to the Nix-store copy of
# `catalog.headscale.aclPolicyFile`; reloading the daemon re-reads it,
# so editing the ACL + running `darwin-rebuild switch` is the full
# apply cycle — no separate `headscale policy set` post-activation
# hook needed.
#
# Clients authenticate via pre-auth keys.  Keys are created on first
# use with `headscale preauthkeys create --user <user>`; they are NOT
# provisioned by this module (one-time bootstrap concern).  Once a
# client registers, re-registrations use the stored node key.
{
  config,
  pkgs,
  lib,
  ndh,
  ...
}:

with lib;

let
  cfg = config.services.headscaleBootstrap;
  catalog = ndh.context.catalog;
  headscaleCatalog = catalog.headscale;
  hostName = config.networking.hostName or "localhost";
  serverUrl =
    if builtins.hasAttr hostName headscaleCatalog.serverUrls then
      headscaleCatalog.serverUrls.${hostName}
    else
      throw "services.headscaleBootstrap enabled on host ${hostName} but catalog.headscale.serverUrls has no entry for it";

  stateDir = "${config.users.users.${config.system.primaryUser}.home}/Library/Application Support/Headscale";
  configFile = "${stateDir}/config.yaml";

  # Headscale config.yaml.  Values substituted in from the catalog.
  # Everything pinned to the state dir so re-activation doesn't relocate
  # running state.  `policy.path` resolves to the Nix store — the file
  # is a symlink target into the flake closure, immutable per generation.
  headscaleConfigYaml = pkgs.writeText "headscale-config.yaml" ''
    # Generated by modules/darwin/headscale-daemon.nix — do not edit by
    # hand.  Persistent state (DB, keys) lives alongside this file under
    # ${stateDir}; the config itself is re-rendered on every
    # darwin-rebuild switch.

    server_url: ${serverUrl}
    listen_addr: 0.0.0.0:${toString headscaleCatalog.listenPort}

    # Metrics listener on localhost only — exposing is optional.
    metrics_listen_addr: 127.0.0.1:${toString (headscaleCatalog.listenPort + 1)}

    # State material headscale creates lazily if missing.
    private_key_path: ${stateDir}/private.key
    noise:
      private_key_path: ${stateDir}/noise_private.key

    # SQLite is fine for a single-operator bootstrap instance.
    database:
      type: sqlite3
      sqlite:
        path: ${stateDir}/db.sqlite

    # ACL policy sourced from the flake catalog.  Store-path means
    # reloading reads whatever the current generation pins; to change
    # the policy, edit catalog/headscale/acl.hujson + darwin-rebuild
    # switch.
    policy:
      mode: file
      path: ${headscaleCatalog.aclPolicyFile}

    # DNS is kept minimal: no MagicDNS override, no extra records.
    # Clients already get their own mDNS resolution; MagicDNS adds a
    # layer we don't need for the 2-operator fleet.
    dns:
      magic_dns: true
      base_domain: mammoth-skate.ts.net
      nameservers:
        global:
          - 1.1.1.1
          - 8.8.8.8

    # Logging: journal-style, info level, stderr so launchd captures
    # into ~/Library/Logs.
    log:
      level: info
      format: text

    # DERP (relays): use the public Tailscale DERP map.  Good enough
    # for LAN + cross-LAN; a self-hosted DERP is a future follow-up.
    derp:
      server:
        enabled: false
      urls:
        - https://controlplane.tailscale.com/derpmap/default
      auto_update_enabled: true
      update_frequency: 24h

    # Disable features we don't use.
    ephemeral_node_inactivity_timeout: 30m
    unix_socket: ${stateDir}/headscale.sock
    unix_socket_permission: "0770"
  '';

  # Thin wrapper that ensures the state dir exists + symlinks the
  # Nix-store config.yaml into it before exec'ing headscale serve.
  # Runtime state (db, keys) remains outside the store; only config is
  # store-pinned.
  headscaleLauncher = pkgs.writeShellScript "headscale-bootstrap-launcher" ''
    set -euo pipefail

    STATE_DIR=${lib.escapeShellArg stateDir}
    CONFIG_LINK=${lib.escapeShellArg configFile}
    CONFIG_SRC=${headscaleConfigYaml}

    mkdir -p "$STATE_DIR"
    chmod 0700 "$STATE_DIR"

    # Symlink so a config edit (via darwin-rebuild switch) is picked up
    # on next daemon restart without copy semantics.  Headscale doesn't
    # care whether the path is a symlink.
    ln -sfn "$CONFIG_SRC" "$CONFIG_LINK"

    exec ${lib.getExe pkgs.headscale} --config "$CONFIG_LINK" serve
  '';
in
{
  options.services.headscaleBootstrap = {
    enable = mkOption {
      type = types.bool;
      default = false;
      description = ''
        Run a headscale server as a user LaunchAgent on this Darwin
        host.  Intended for the bootstrap phase, before a production
        instance takes over from inside the rke2 cluster.  URL +
        port are sourced from catalog.headscale.
      '';
    };
  };

  config = mkIf cfg.enable {
    # Install the CLI system-wide so the operator can run
    # `headscale users create`, `headscale preauthkeys create`, etc.
    # without fishing for the store path.
    environment.systemPackages = [ pkgs.headscale ];

    # Register the port in /etc/services so `lsof -iTCP -sTCP:LISTEN`,
    # netstat, and similar tools render a descriptive name.  macOS
    # ships /etc/services as a real file (not nix-darwin managed), so
    # we append via activation rather than environment.etc.
    system.activationScripts.postActivation.text = lib.mkAfter ''
      if ! grep -qE '^${headscaleCatalog.serviceName}\s+${toString headscaleCatalog.listenPort}/tcp' /etc/services 2>/dev/null; then
        printf '%s\n' '${headscaleCatalog.serviceName} ${toString headscaleCatalog.listenPort}/tcp # Headscale bootstrap control-plane (modules/darwin/headscale-daemon.nix)' >> /etc/services
      fi
    '';

    launchd.user.agents.headscale-bootstrap = {
      command = "${headscaleLauncher}";
      serviceConfig = {
        Label = "io.nxmatic.nix-darwin-home.headscale-bootstrap";
        # Restart on crash.  Headscale is long-lived; transient
        # failures (port binding, DB lock) resolve themselves.
        KeepAlive = true;
        RunAtLoad = true;
        # Logs: stdout/stderr both go to the user's Logs folder so
        # `tail -f ~/Library/Logs/headscale-bootstrap.log` works.
        StandardOutPath = "${config.users.users.${config.system.primaryUser}.home}/Library/Logs/headscale-bootstrap.log";
        StandardErrorPath = "${config.users.users.${config.system.primaryUser}.home}/Library/Logs/headscale-bootstrap.err.log";
        # launchd policy hints.
        ProcessType = "Background";
        LowPriorityIO = true;
      };
    };
  };
}
