#!/usr/bin/env -S bash -euo pipefail
# -*- mode: sh -*-

test -n "${GIT_TRACE:-}" && set -x

# Exit if the operation and file names were not given
test $# -ge 2

# Exit if no stdin available.
# stdin is used to fed sops with the content to encrypt / decrypt.
test ! -t 0

git::sops:input:yq:format() {
  case "${META[fileExt]}" in
    "yml"|"yaml")
      echo "yaml";;
    "json")
      echo "json";;
    "xml")
      echo "xml";;
    "env|dotenv|props|properties")
      echo "properties";;
    "csv")
      echo "csv";;
    "tsv")
      echo "tsv";;
    "base64"|"b64")
      echo "base64";;
    "uri")
      echo "uri";;
    "toml")
      echo "toml";;
    "lua")
      echo "lua";;
    *)
      echo "unsupported";;
  esac
}


git::sops:show() {
  printf "%s\n" "${@}"
}

# Append or strip the git sops trailer
GIT_SOPS_TRAILER="git::sops:trailer"

git::sops:input:trailer:concat() {
  cat <<!
  ${1:-$( cat /dev/stdin )}
  ${GIT_SOPS_TRAILER}
!
}

git::sops:input:trailer:strip() {
  echo "${1%${GIT_SOPS_TRAILER}}"
}

# Wrapper
git::sops() {
  local operation="$1"
  case $operation in
    show)
      git::sops:show "${@:2}"
      ;;
    decrypt|encrypt)
      local filecontent="$( cat /dev/stdin )"
      
      [[ -z "${filecontent}" ]] &&
	return

      local operation="${1}"

      git::sops::${operation} <<<"${filecontent}"
      ;;
  esac
}

# First arg passed to script.
# clean is meant to call sops encrypt
# smudge is meant to call sops decrypt
OP="${1}"

# Second arg passed to script
# The file name is fed to sops --filename-override so that sops can apply the creation_rules
# based on .sops.yaml file in the root of the repo.
declare -A META=(
  [fileName]="$( basename "${2}" )"
  [fileExt]="${2##*.}"
)

# Third arg passed to script
META[fileFormat]=${3:-$( git::sops:input:yq:format ${META[fileExt]} )}

if [[ -n "${META[fileFormat]}" && "${META[fileFormat]}" != "unsupported" ]]; then
  git::sops::encrypt() {
    yq -o yaml eval . /dev/stdin |
      sops --encrypt --input-type yaml --filename-override "${META[fileName]}" /dev/stdin
  }
  git::sops::decrypt() {
      sops --decrypt --input-type yaml --filename-override "${META[fileName]}" /dev/stdin |
    yq -i yaml -o ${META[fileFormat]} eval . /dev/stdin
  }
else
  git::sops::encrypt() {
    sops --encrypt --input-type binary --filename-override "${META[fileName]}" /dev/stdin
  }
  git::sops::decrypt() {
    sops --decrypt --input-type binary --filename-override "${META[fileName]}" /dev/stdin
  }
fi

case "${OP}" in
  "smudge")
    # Just decrypt the stdin contents.
    TMP=$(mktemp)
    DECRYPTED=$( git::sops decrypt </dev/stdin 2> "$TMP" )
    err=$(cat "$TMP")
    rm "$TMP"
    wrong_key_error_message="age: no identity matched any of the recipients"
    if [[ $err == *"${wrong_key_error_message}"* ]]; then
      :
    else
      git::sops show "${DECRYPTED}"
    fi
    ;;
  "clean")
    # Either the file was not committed yet, or the existing decrypted content is different
    # from the input, in which case we output the new encrypted input.
    # If the file was commited and its decrypted content is the same as the new input,
    # output the old encrypted content.
    ENCRYPTED_HEAD_CONTENTS="$( git cat-file -p "HEAD:${META[fileName]}" 2>/dev/null || true )"
    DECRYPTED_HEAD_CONTENTS="$( git::sops decrypt <<<"${ENCRYPTED_HEAD_CONTENTS}" )"
    
    INPUT="$( cat /dev/stdin )"

    if [[ -z "${ENCRYPTED_HEAD_CONTENTS}" || "${DECRYPTED_HEAD_CONTENTS}" != "${INPUT}" ]]; then
      OUTPUT="$( git::sops encrypt <<<"${INPUT}" 2>/dev/null )"
    else
      OUTPUT="${ENCRYPTED_HEAD_CONTENTS}"
    fi
    git::sops show "${OUTPUT}"
    ;;
  *)
    exit 1;;
esac

