#!/usr/bin/env -S bash -euo pipefail
# Render headscale config.yaml from a Nix-built JSON document.
#
# Inputs (substituted by pkgs.replaceVars at build time):
#   @nixBashTrampoline@ — path to the canonical bash trampoline
#   @configJson@        — path to the JSON document with all config values
#   @loggerTag@         — logger tag for the activation framework
#
# The JSON shape is exactly the headscale config schema (1:1 keys), with
# every value already typed correctly for YAML emission.  We hand it to
# yq with `-p json -o yaml` so the YAML nesting / list indentation is
# always correct — no manual string concatenation, no indent footguns.
#
# Comments don't survive the JSON → YAML round-trip; rationale lives in
# the Nix module instead (modules/{darwin,nixos}/headscale-daemon.nix).
# A single header banner is injected here so anyone reading the rendered
# file knows it's generated.

# shellcheck disable=SC1091
source @nixBashTrampoline@

main() {
	local outputFile="$1"
	local headerBanner
	headerBanner=$(cat <<'EOF'
# Generated by modules/.common.d/headscale-daemon.d/render-config.sh.
# Do not edit by hand — re-rendered on every system rebuild from the
# catalog at catalog/default.nix and the platform module at
# modules/{darwin,nixos}/headscale-daemon.nix.
EOF
)

	# yq's `-p json -o yaml` round-trip guarantees correct YAML
	# indentation regardless of nesting depth.  `--no-doc` would suppress
	# the leading `---` (default yq omits it for single-doc output, so
	# nothing to do).
	{
		printf '%s\n' "$headerBanner"
		yq -p json -o yaml '.' "@configJson@"
	} > "$outputFile"
}

ndh::logger:command:run "@loggerTag@" main "$@"
