{
  config,
  lib,
  ndh,
  pkgs,
  ...
}:
# Platform-agnostic nix-store identity options.
#
# Data layer: the `nix-store` entry in keys.yaml produces a rotating
# keypair signed by mammoth-skate. The enrich+extract pipeline writes
# the usable material under the NDH-managed system-keys root:
#   ${sshPaths.systemKeysDir}/nix-store            (private, 0600)
#   ${sshPaths.systemKeysDir}/nix-store-cert.pub   (symlink → user cert)
#
# Consumers (the `nix-store.<peer>` ssh alias, `nix copy --to`
# from bioskop during remote bringup activation) read those paths
# directly — there is no /etc/nix/ copy. The ssh
# alias is the single source of truth for nix-store outbound auth; any
# new consumer should go through `ssh-ng://nix-store.<host>` and let
# the alias supply IdentityFile + CertificateFile.
#
# Per-platform specifics (inbound nix-store user provisioning) live in:
#
#   - modules/darwin/nix-store-identity.nix
#   - modules/nixos/nix-store-identity.nix
let
  cfg = config.nixStoreIdentity;

  ndhContext = lib.attrByPath [ "context" ] { } ndh;
  inventoryHostNames = builtins.attrNames (lib.attrByPath [ "inventory" "hosts" ] { } ndhContext);
  selfHostName = config.networking.hostName or "";
  peerHostNames = lib.filter (h: h != selfHostName && h != "") inventoryHostNames;

  # Restricted login shell for the inbound nix-daemon user. Rendered as a
  # writeShellApplication so the file is 0555 and shellcheck-clean; the
  # passthru.shellPath override is mandatory for NixOS's users-groups
  # validator to accept the package as a login shell.
  #
  # Using a store-path shell (rather than /etc/ssh/nix-store-shell)
  # sidesteps Darwin's /etc permission surface — nix-darwin's
  # environment.etc does not honour `mode`, and the /etc/static/<…>
  # symlink chain it materializes points at a 0444 store file, which
  # sshd rejects with "shell is not executable".
  inboundUserShell =
    (pkgs.writeShellApplication {
      name = "nix-store-shell";
      text = ''
        exec /run/current-system/sw/bin/nix-daemon --stdio
      '';
    }).overrideAttrs
      (_: {
        passthru.shellPath = "/bin/nix-store-shell";
        meta.shellPath = "/bin/nix-store-shell";
      });

  # Per-host stanza. CertificateFile is mandatory: with cert-signed auth,
  # ssh must present the cert alongside the private or sshd will not
  # match the TrustedUserCAKeys / AuthorizedPrincipalsCommand pair.
  peerStanza = host: ''
    Host nix-store.${host}
      HostName ${host}${cfg.hostSuffix}
      User nix-store
      IdentityFile ${cfg.keyPath}
      CertificateFile ${cfg.certPath}
      IdentitiesOnly yes
      AddKeysToAgent no
      StrictHostKeyChecking accept-new
  '';

  sshClientFragmentText =
    "# Generated by modules/.common.d/nix-store-identity.nix (@codebase)\n"
    + lib.concatMapStringsSep "\n" peerStanza peerHostNames;
in
{
  imports = [ ./ssh-paths.nix ];

  options.nixStoreIdentity = {
    enable = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = "Whether to expose the nix-store identity deploy helpers on this host.";
    };

    keyPath = lib.mkOption {
      type = lib.types.str;
      default = "${config.sshPaths.systemKeysDir}/nix-store";
      description = ''
        Path to the nix-store private key. Written directly by the
        ssh-keys enrich/extract pipeline under sshPaths.systemKeysDir —
        no separate deploy step. Bound as IdentityFile in the
        `nix-store.<peer>` ssh alias.
      '';
    };

    certPath = lib.mkOption {
      type = lib.types.str;
      default = "${config.sshPaths.systemKeysDir}/nix-store-cert.pub";
      description = ''
        Path to the nix-store user certificate. Written as a symlink by
        the ssh-keys enrich/extract pipeline. Bound as CertificateFile
        in the `nix-store.<peer>` ssh alias; ssh-client follows symlinks.
      '';
    };

    provisionInboundUser = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = ''
        Provision a local `nix-store` system user that serves inbound
        `nix-daemon --stdio` connections, register it as a trusted nix
        user, and expose its login shell. The user itself is declared
        in the platform module (modules/darwin/nix-store-identity.nix
        or modules/nixos/nix-store-identity.nix) because Darwin and
        NixOS need different option surfaces.
      '';
    };

    inboundUserName = lib.mkOption {
      type = lib.types.str;
      default = "nix-store";
      description = "Login name of the inbound nix-daemon user.";
    };

    inboundUserUid = lib.mkOption {
      type = lib.types.int;
      default = 630;
      description = ''
        POSIX UID for the inbound nix-daemon user. Darwin needs an
        explicit UID in users.knownUsers; NixOS ignores this field and
        auto-allocates instead.
      '';
    };

    inboundUserShellPackage = lib.mkOption {
      type = lib.types.package;
      default = inboundUserShell;
      description = ''
        Package providing the restricted login shell for the inbound
        nix-daemon user. Carries `meta.shellPath` + `passthru.shellPath`
        so NixOS's users-groups validator accepts it.
      '';
    };

    inboundUserShellPath = lib.mkOption {
      type = lib.types.str;
      default = "${cfg.inboundUserShellPackage}${cfg.inboundUserShellPackage.shellPath}";
      description = "Absolute path to the inbound user's login shell inside its store package.";
    };

    hostSuffix = lib.mkOption {
      type = lib.types.str;
      default = ".local";
      description = "Suffix appended to each inventory hostname when building the reachable HostName.";
    };

    sshClientFragment = lib.mkOption {
      type = lib.types.str;
      readOnly = true;
      description = "Rendered /etc/ssh/ssh_config.d fragment exposing Host nix-store.<peer> aliases.";
    };
  };

  config = lib.mkIf cfg.enable {
    nixStoreIdentity.sshClientFragment = sshClientFragmentText;

    environment.etc."ssh/ssh_config.d/75-nix-store.conf" = lib.mkIf (peerHostNames != [ ]) {
      text = sshClientFragmentText;
    };

    # Register the restricted shell + grant the user nix-daemon trust.
    # Both options are platform-agnostic (environment.shells exists on
    # Darwin and NixOS; nix.settings.trusted-users likewise). The user
    # *record* itself is declared in the platform module.
    environment.shells = lib.mkIf cfg.provisionInboundUser [ cfg.inboundUserShellPath ];
    nix.settings.trusted-users = lib.mkIf cfg.provisionInboundUser [ cfg.inboundUserName ];
  };
}
