{
  config,
  lib,
  ndh,
  pkgs,
  ...
}:
# Platform-agnostic nix-store identity options + deploy script.
#
# Data layer: the `nix-store` entry in keys.yaml (commit 530eb299)
# produces a rotating keypair signed by mammoth-skate. The per-user
# enrich+extract pipeline materializes:
#   ${sshPaths.systemKeysDir}/nix-store            (private, 0600)
#   ${sshPaths.systemKeysDir}/nix-store-cert.pub   (symlink → user cert)
#
# Consumers (nix-daemon --stdio, `nix copy`) expect the identity at a
# stable system path. Per-platform wiring (user provisioning, how to
# run the deploy script at activation) lives in:
#
#   - modules/darwin/nix-store-identity.nix
#   - modules/nixos/nix-store-identity.nix
#
# Both platform modules read ndh.nixStoreIdentity.deployScript and
# inboundUserShellPackage from the options declared here.
let
  cfg = config.nixStoreIdentity;

  ndhContext = lib.attrByPath [ "context" ] { } ndh;
  inventoryHostNames = builtins.attrNames (lib.attrByPath [ "inventory" "hosts" ] { } ndhContext);
  selfHostName = config.networking.hostName or "";
  peerHostNames = lib.filter (h: h != selfHostName && h != "") inventoryHostNames;

  # Restricted login shell for the inbound nix-daemon user. Rendered as a
  # writeShellApplication so the file is 0555 and shellcheck-clean; the
  # passthru.shellPath override is mandatory for NixOS's users-groups
  # validator to accept the package as a login shell.
  #
  # Using a store-path shell (rather than /etc/ssh/nix-store-shell)
  # sidesteps Darwin's /etc permission surface — nix-darwin's
  # environment.etc does not honour `mode`, and the /etc/static/<…>
  # symlink chain it materializes points at a 0444 store file, which
  # sshd rejects with "shell is not executable".
  inboundUserShell =
    (pkgs.writeShellApplication {
      name = "nix-store-shell";
      text = ''
        exec /run/current-system/sw/bin/nix-daemon --stdio
      '';
    }).overrideAttrs
      (_: {
        passthru.shellPath = "/bin/nix-store-shell";
        meta.shellPath = "/bin/nix-store-shell";
      });

  # Per-host stanza. CertificateFile is mandatory: with cert-signed auth,
  # ssh must present the cert alongside the private or sshd will not
  # match the TrustedUserCAKeys / AuthorizedPrincipalsCommand pair.
  peerStanza = host: ''
    Host nix-store.${host}
      HostName ${host}${cfg.hostSuffix}
      User nix-store
      IdentityFile ${cfg.keyPath}
      CertificateFile ${cfg.certPath}
      IdentitiesOnly yes
      AddKeysToAgent no
      StrictHostKeyChecking accept-new
  '';

  sshClientFragmentText =
    "# Generated by modules/.common.d/nix-store-identity.nix (@codebase)\n"
    + lib.concatMapStringsSep "\n" peerStanza peerHostNames;
in
{
  imports = [ ./ssh-paths.nix ];

  options.nixStoreIdentity = {
    enable = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = "Whether to expose the nix-store identity deploy helpers on this host.";
    };

    keyDir = lib.mkOption {
      type = lib.types.str;
      default = "/etc/nix";
      description = "Directory holding the deployed nix-store identity files.";
    };

    keyPath = lib.mkOption {
      type = lib.types.str;
      default = "${cfg.keyDir}/nix-store_ed25519";
      description = "Destination path for the deployed nix-store private key.";
    };

    certPath = lib.mkOption {
      type = lib.types.str;
      default = "${cfg.keyDir}/nix-store-cert.pub";
      description = "Destination path for the deployed nix-store user certificate.";
    };

    sourcePrivate = lib.mkOption {
      type = lib.types.str;
      default = "${config.sshPaths.systemKeysDir}/nix-store";
      description = "Source path of the extracted private key (written by the enrich/extract pipeline).";
    };

    sourceCert = lib.mkOption {
      type = lib.types.str;
      default = "${config.sshPaths.systemKeysDir}/nix-store-cert.pub";
      description = "Source path of the user certificate symlink (written by the enrich/extract pipeline).";
    };

    installGroup = lib.mkOption {
      type = lib.types.str;
      description = ''
        Group ownership for files installed by the deploy script. Must
        be set by each platform module (wheel on Darwin, root on NixOS)
        — no default here so cross-platform assumptions are never baked
        into the common layer.
      '';
    };

    provisionInboundUser = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = ''
        Provision a local `nix-store` system user that serves inbound
        `nix-daemon --stdio` connections, register it as a trusted nix
        user, and expose its login shell. The user itself is declared
        in the platform module (modules/darwin/nix-store-identity.nix
        or modules/nixos/nix-store-identity.nix) because Darwin and
        NixOS need different option surfaces.
      '';
    };

    inboundUserName = lib.mkOption {
      type = lib.types.str;
      default = "nix-store";
      description = "Login name of the inbound nix-daemon user.";
    };

    inboundUserUid = lib.mkOption {
      type = lib.types.int;
      default = 630;
      description = ''
        POSIX UID for the inbound nix-daemon user. Darwin needs an
        explicit UID in users.knownUsers; NixOS ignores this field and
        auto-allocates instead.
      '';
    };

    inboundUserShellPackage = lib.mkOption {
      type = lib.types.package;
      default = inboundUserShell;
      description = ''
        Package providing the restricted login shell for the inbound
        nix-daemon user. Carries `meta.shellPath` + `passthru.shellPath`
        so NixOS's users-groups validator accepts it.
      '';
    };

    inboundUserShellPath = lib.mkOption {
      type = lib.types.str;
      default = "${cfg.inboundUserShellPackage}${cfg.inboundUserShellPackage.shellPath}";
      description = "Absolute path to the inbound user's login shell inside its store package.";
    };

    hostSuffix = lib.mkOption {
      type = lib.types.str;
      default = ".lan";
      description = "Suffix appended to each inventory hostname when building the reachable HostName.";
    };

    sshClientFragment = lib.mkOption {
      type = lib.types.str;
      readOnly = true;
      description = "Rendered /etc/ssh/ssh_config.d fragment exposing Host nix-store.<peer> aliases.";
    };

    deployScript = lib.mkOption {
      type = lib.types.package;
      readOnly = true;
      description = "Package exposing bin/nix-store-identity-deploy.";
    };
  };

  config = lib.mkIf cfg.enable {
    nixStoreIdentity.sshClientFragment = sshClientFragmentText;

    environment.etc."ssh/ssh_config.d/75-nix-store.conf" = lib.mkIf (peerHostNames != [ ]) {
      text = sshClientFragmentText;
    };

    nixStoreIdentity.deployScript = ndh.store.writeShellScriptBin "nix-store-identity-deploy" ''
      set -euo pipefail

      install -d -m 0755 "${cfg.keyDir}"

      if [ -f "${cfg.sourcePrivate}" ]; then
        install -m 0600 -o root -g ${cfg.installGroup} "${cfg.sourcePrivate}" "${cfg.keyPath}"
      else
        echo "nix-store-identity: private key not yet deployed at ${cfg.sourcePrivate}" >&2
      fi

      # Resolve the cert symlink before copying so the destination holds
      # the real contents rather than a link into the home-manager
      # secrets tree.
      if [ -e "${cfg.sourceCert}" ]; then
        install -m 0644 -o root -g ${cfg.installGroup} "$(readlink -f "${cfg.sourceCert}")" "${cfg.certPath}"
      else
        echo "nix-store-identity: user certificate not yet deployed at ${cfg.sourceCert}" >&2
      fi
    '';

    # Register the restricted shell + grant the user nix-daemon trust.
    # Both options are platform-agnostic (environment.shells exists on
    # Darwin and NixOS; nix.settings.trusted-users likewise). The user
    # *record* itself is declared in the platform module.
    environment.shells = lib.mkIf cfg.provisionInboundUser [ cfg.inboundUserShellPath ];
    nix.settings.trusted-users = lib.mkIf cfg.provisionInboundUser [ cfg.inboundUserName ];
  };
}
