Host linux-builder
  IdentityFile none
  IdentityFile "~/.local/var/run/secrets/ssh-keys/linux-builder"
  IdentitiesOnly yes
  User builder
  ForwardAgent yes  # ensure agent forwarding even if agent-forwarding.conf not yet loaded