# WAN gateway to mammoth-skate LAN via bioskop
# SSH tunnel for off-LAN access to headscale control plane and DNS

Host *.mammoth-skate
  HostName mammoth-skate.duckdns.org
  Port 2222
  User nxmatic
  ExitOnForwardFailure yes
  ServerAliveInterval 30
  ServerAliveCountMax 3

Host headscale.mammoth-skate
  LocalForward 127.0.0.1:41841 127.0.0.1:41841

Host rdp.mammoth-skate
  LocalForward 0.0.0.0:5901 localhost:5900
